version: "3.7"
services:
  screeps:
    container_name: screeps
    image: qnimbus/docker-screeps
    build: ./
    networks:
      - screeps
    volumes:
      - /srv/containers/data/screeps:/screeps
    ports:
      - 21025:21025
      - 21026:21026
    environment:
      - STEAM_KEY=
      - LOCAL_UID=1101
      - GAME_PORT=21025
      - CLI_PORT=21026
    restart: "no"
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - screeps
    volumes:
      - /srv/containers/databases/screeps/data:/data/db
      - /srv/containers/databases/screeps/config:/data/configdb
    restart: "no"
  redis:
    container_name: redis
    image: redis
    networks:
      - screeps
    volumes:
      - /srv/containers/data/screeps-redis:/data
    restart: "no"

networks:
  screeps:
    name: screeps_net
    driver: bridge
